// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.WorkingDays
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("workingDaysCount")]
        public long WorkingDaysCount { get; set; }

        [JsonProperty("nonWorkingDaysCount")]
        public long NonWorkingDaysCount { get; set; }

        [JsonProperty("workingDays")]
        public DateTimeOffset[] WorkingDays { get; set; }

        [JsonProperty("nonWorkingDays")]
        public NonWorkingDay[] NonWorkingDays { get; set; }
    }

    public partial class NonWorkingDay
    {
        [JsonProperty("date")]
        public DateTimeOffset Date { get; set; }

        [JsonProperty("reasons")]
        public Reason[] Reasons { get; set; }

        [JsonProperty("holiday_name")]
        public string HolidayName { get; set; }
    }

    public enum Reason { PublicHoliday, Weekend };
}
